global using System.Numerics;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using Windows.Win32;
global using Windows.Win32.Foundation;
global using Windows.Win32.Graphics.Gdi;
global using Windows.Win32.Graphics.GdiPlus;
global using Windows.Win32.UI.Input.KeyboardAndMouse;
global using Windows.Win32.UI.WindowsAndMessaging;
global using RectangleF = System.Drawing.RectangleF;
